version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1